### ISSUE TITLE
App not running with instructions

### ISSUE THREAD

**Issue by HussainWillow** [guruvn/willow-puzzle#1]
Hi Nguyen, we are trying to run your app but it's not working. After following the two instructions (npm install + npm run build) it is complaining on the second one, it is complaining with the following:

> Error: Cannot find module '.../willow-puzzle/Task 3/Puzzle.App/build/Webpack.config.js'

This file is being referenced inside package.json.

Can you please fix this so it has all the necessary files and instructions? Thanks :)

**Comment by guruvn** [comment]
@HussainWillow : Many thanks for the response. It was an issue with my `.gitignore` file. I have corrected the ignore file as well as added `run-dev.ps1` to simplify and facilitate running the application.

Kindly let me know should you have any further question
